<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KSR" failures="4" tests="11" name="Test" time="6.701" errors="0" timestamp="2022-09-22T20:39:07 IST">
  <testcase classname="TestNG.SoftAssert_Testing" name="SoftAssrt_Test" time="0.011">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [11] but found [10]
at TestNG.SoftAssert_Testing.SoftAssrt_Test(SoftAssert_Testing.java:25)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- SoftAssrt_Test -->
  <testcase classname="TestNG.HardAssert" name="HardAssert_Test" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10]
at TestNG.HardAssert.HardAssert_Test(HardAssert.java:16)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- HardAssert_Test -->
  <testcase classname="TestNG.TestNg_Annotation_Order" name="B_UrlTest" time="0.007"/>
  <testcase classname="TestNG.TestNg_Annotation_Order" name="A_lrtTest" time="0.002"/>
  <testcase classname="TestNG.SoftAssert_Testing" name="SoftAssrt_Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [11] but found [10],
	expected [11] but found [100]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [11] but found [10],
expected [11] but found [100]
at TestNG.SoftAssert_Testing.SoftAssrt_Test2(SoftAssert_Testing.java:41)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- SoftAssrt_Test2 -->
  <testcase classname="TestNG.TestNg_Annotation_Order" name="Test_Check" time="0.002"/>
  <testcase classname="TestNG.TestNg_Annotation_Uses" name="B_UrlTest" time="1.402"/>
  <testcase classname="TestNG.Validations_Using_Assertions" name="TittleValidation" time="0.015"/>
  <testcase classname="TestNG.Validations_Using_Assertions" name="boolenValidation" time="2.129">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at TestNG.Validations_Using_Assertions.boolenValidation(Validations_Using_Assertions.java:78)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- boolenValidation -->
  <testcase classname="TestNG.TestNg_Annotation_Uses" name="A_lrtTest" time="3.243"/>
  <testcase classname="TestNG.TestNg_Annotation_Uses" name="Test_Check" time="0.003"/>
</testsuite> <!-- Test -->
